### PR TITLE
fw/popups/phone_ui: fix call duration timer showing on unanswered calls

### LINKED ISSUE #808: Duration of not answered call is showing
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Sometimes I'm getting call duration, an abnormal one. Without answering at all.

Image

### Expected Behavior

Not get a call duration, until call is answered.

### Steps To Reproduce

1. Get an incoming call
2. Do not answer it
3. See abnormal call duration anyway

### Version

4.9.122

### Host OS

N/A

### Watch

Pebble 2 Duo (Asterix)

### Anything else?

I was about to leave a bug report through mobile app, but bug report wasn't uploading...

### PR DESCRIPTION
**Pull request by spr4bhu**
This PR complements the mobileapp fix ([coredevices/mobileapp#124](https://github.com/coredevices/mobileapp/pull/124)) by adding guards against stale call_start_time values and explicit status text handling for all call end scenarios.

Changes:

- Add call_start_time == 0 guard in prv_update_call_time() — if the timer callback fires after being stopped, it won't compute a duration from a stale timestamp
- Reset call_start_time = 0 in prv_stop_call_duration_timer() — ensures no stale timestamp can persist after stopping the timer
- Add CallStatus.ENDED enum and update prv_set_status_text() to explicitly handle ENDED — replaces the heuristic that used call_start_time to infer "Call Ended" vs "Call Declined"
- Update phone_ui_handle_call_end() to use ENDED for unanswered calls (caller hangs up before answer) instead of DECLINED
- Update phone_ui_handle_call_hide() for iOS unanswered calls to show "Call Ended" with proper end-of-call UI (icon, color, delay) instead of immediately popping the window

Closes #808

### CODE REVIEW

File: src/fw/popups/phone_ui.c [hunk 1]
```diff
@@ -1174,23 +1177,31 @@ void phone_ui_handle_call_end(bool call_accepted, bool disconnected) {
...
+  if (!s_phone_ui_data) {
+    return;
+  }
+  prv_stop_ringing();
+  prv_stop_call_duration_timer();
+  prv_action_bar_setup(PhoneCallActions_None);
+  prv_set_icon_resource(TIMELINE_RESOURCE_DISMISSED_PHONE_CALL);
+  prv_set_window_color(DECLINE_COLOR, true);
+  prv_set_status_text(ENDED);
+  prv_window_pop_with_delay(CALL_END_DELAY_MS);
```
Comment (gmarull) [inline src/fw/popups/phone_ui.c]: this looks overcomplicated compared to the previous impl

File: src/fw/popups/phone_ui.c [hunk 2]
```diff
@@ -1174,23 +1177,31 @@ void phone_ui_handle_call_end(bool call_accepted, bool disconnected) {
...
+    prv_set_status_text(ENDED);
   } else {
     prv_set_icon_resource(TIMELINE_RESOURCE_DISMISSED_PHONE_CALL);
     prv_set_window_color(DECLINE_COLOR, true);
     if (disconnected) {
       prv_set_status_text(DISCONNECTED);
     } else {
-      prv_set_status_text(DECLINED);
+      prv_set_status_text(ENDED);
     }
```
Comment (gmarull) [inline src/fw/popups/phone_ui.c:1188]: both branches now set 'ENDED', code is hard to follow

**Review by gmarull — CHANGES_REQUESTED** [review]
please, follow commit guidelines

File: src/fw/popups/phone_ui.c (hunk 1 above)
Comment (spr4bhu) [reply src/fw/popups/phone_ui.c]: The previous phone_ui_handle_call_hide() just called prv_window_pop() which silently dismissed the UI with no status text or delay

I will simplify it to reuse the phone_ui_handle_call_end(bool call_accepted, bool disconnected) function

File: src/fw/popups/phone_ui.c (hunk 2 above)
Comment (spr4bhu) [reply src/fw/popups/phone_ui.c:1188]: Both branches set ENDED because the status text is always 'Call Ended' regardless of whether the call was answered (The status appears on screen only when the call ends so ACCEPTED is the wrong thing to display)

the if else only controls the icon and colour

File: src/fw/popups/phone_ui.c [hunk 3]
```diff
@@ -1174,23 +1177,22 @@ void phone_ui_handle_call_end(bool call_accepted, bool disconnected) {
   if (call_accepted) {
     prv_set_icon_resource(TIMELINE_RESOURCE_DURING_PHONE_CALL);
     prv_set_window_color(ACCEPT_COLOR, true);
-    prv_set_status_text(ACCEPTED);
+    prv_set_status_text(ENDED);
```
Comment (gmarull) [inline src/fw/popups/phone_ui.c:1180]: While call has ended, it was ended but initially accepted, so should be kept as is unless it was previously wrong.

File: src/fw/popups/phone_ui.c [hunk 4]
```diff
@@ -1174,23 +1177,22 @@ void phone_ui_handle_call_end(bool call_accepted, bool disconnected) {
...
   } else {
     prv_set_icon_resource(TIMELINE_RESOURCE_DISMISSED_PHONE_CALL);
     prv_set_window_color(DECLINE_COLOR, true);
     if (disconnected) {
       prv_set_status_text(DISCONNECTED);
     } else {
-      prv_set_status_text(DECLINED);
+      prv_set_status_text(ENDED);
```
Comment (jplexer) [inline src/fw/popups/phone_ui.c]: Should still say call declined

File: src/fw/popups/phone_ui.c [hunk 5]
```diff
@@ -1174,23 +1177,22 @@ void phone_ui_handle_call_end(bool call_accepted, bool disconnected) {
...
     }
   }
 
   prv_window_pop_with_delay(CALL_END_DELAY_MS);
 }
 
 void phone_ui_handle_call_hide(void) {
-  // Just pop the window - it'll handle all the cleanup
-  prv_window_pop();
+  phone_ui_handle_call_end(false /* call_accepted */, false /* disconnected */);
```
Comment (jplexer) [inline src/fw/popups/phone_ui.c]: call hide should hide the ui, not display something before hiding
