### PR TITLE
fw/drivers/sf32lb52/display_jdi: use LPCLOCK for LPTIM

### LINKED ISSUE #428: VCOM/xFRP JDI signals not working with stop mode on SF32LB52/Obelix
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

With stop mode enabled:

Image

With stop mode disabled:

Image

### Expected Behavior

VCOM/xFRP signals are ALWAYS on; otherwise, display ghosting occurs.

### Steps To Reproduce

Does not work:

```
./waf configure --board obelix_bb2
./waf build_prf
./waf flash_prf --tty ...
./waf console_prf --tty ...
```

Works:

```
./waf configure --board obelix_bb2 --nostop
./waf build_prf
./waf flash_prf --tty ...
./waf console_prf --tty ...
```

### Version

9d3a9548f6d333aaca95973aab5ee559a4250751

### Host OS

N/A

### Watch

Pebble Time 2 (Obelix)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by gmarull**
Otherwise LPTIM cannot be clocked in deepsleep, causing VCOM/xFRP to stop functioning. Scoped signals to verify they are on all the time now.

Fixes #428

### CODE REVIEW

File: src/fw/drivers/sf32lb52/display_jdi.c [hunk 1]
```diff
@@ -92,8 +93,8 @@ static void prv_display_on() {
 
   LPTIM_TypeDef *lptim = DISPLAY->vcom.lptim;
 
-  lptim->CFGR |= LPTIM_INTLOCKSOURCE_APBCLOCK;
-  lptim->ARR = 3750000 / DISPLAY->vcom.freq_hz;
+  lptim->CFGR |= LPTIM_INTCLOCKSOURCE_LPCLOCK;
+  lptim->ARR = RC10K_FREQ / DISPLAY->vcom.freq_hz;
```
Comment (rabbitsaviola) [inline src/fw/drivers/sf32lb52/display_jdi.c:97]: is it possible to use xtal32k as clock source of RTC in the future?

Comment (gmarull) [reply src/fw/drivers/sf32lb52/display_jdi.c:97]: Nope, as we do not have pins left for 32k osc....

Comment (gmarull) [reply src/fw/drivers/sf32lb52/display_jdi.c:97]: JDI takes too much pins :laughing:

**Review by rabbitsaviola — APPROVED** [review]
