### PR TITLE
fw: re-enable microphone and fix OOM issues

### LINKED ISSUE #167: OOM problems during phone calls
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

System will exhaust available memory when e.g. receiving a phone call (for me a couple of calls are enough to trigger it). Apparently reverting microphone support on Asterix seems to "mitigate" the problem.

### Expected Behavior

No OOM.

### Steps To Reproduce

Reapply

https://github.com/coredevices/PebbleOS/commit/0fbb8671469a8a5e205af8f73b8b6dd69ca19f5a
https://github.com/coredevices/PebbleOS/commit/65fbe5846272cb37154af3e5dcdae9ab1a6afd97
https://github.com/coredevices/PebbleOS/commit/71b670fd9ce0e13cc40cedbf8c17bfd514da97c0

Flash firmware on Asterix and make yourself a few phone calls.

### Environment

```markdown
- **OS**: Linux
- **Watch**: Asterix
```

### Anything else?

Reverted microphone support on Asterix while this is investigated. FYI: @jplexer

### PR DESCRIPTION
**Pull request by jplexer**
The reason for the OOM issues was we initialized a speex encoder on service launch, which of course takes memory away.

Fixes #167

### CODE REVIEW

File: src/fw/services/normal/voice/voice.c [hunk 1]
```diff
@@ -338,6 +334,15 @@ VoiceSessionId voice_start_dictation(VoiceEndpointSessionType session_type) {
...
   mutex_lock(s_lock);
 
+  // Lazily initialize Speex encoder to avoid baseline memory usage when voice not used
+  if (!voice_speex_is_initialized()) {
+    if (!voice_speex_init()) {
+      PBL_LOG(LOG_LEVEL_ERROR, "Failed to initialize Speex encoder");
+      mutex_unlock(s_lock);
+      return VOICE_SESSION_ID_INVALID;
+    }
+  }
```
Comment (gmarull) [inline src/fw/services/normal/voice/voice.c:355]: is it ever de-initialized? ie, when init happens, can you reproduce after issues like calls crashing due to OOM?

Comment (jplexer) [reply src/fw/services/normal/voice/voice.c:355]: nope, but we totally should. have added it

**Review by gmarull — APPROVED** [review]
Let me test before merging, but lgtm
